# Generated by Django 3.2.12 on 2022-05-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price1',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
